# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

group_and_reduce_phenotypes <- function(phenotypes, markers_to_drop) {
    .Call('_PhenoComb_group_and_reduce_phenotypes', PACKAGE = 'PhenoComb', phenotypes, markers_to_drop)
}

#' Generates a human-readable phenotype name
#'
#' \code{make_phenotype_name} generates a human-readable phenotype name from a numeric representation
#' with the following encoding:
#' -1 : Drop marker
#' 0  : - (negative)
#' 1  : + (positive)
#' 2  : ++ (double positive)
#' More positive states can also be represented (e.g. 3, 4... : +++, ++++...)
#'
#' @param phenotype Numeric vector with phenotype encoding.
#' @param markers Names for markers. Must match the length of \code{phenotype}.
#' @return Phenotype name.
#'
#' @examples
#' make_phenotype_name(c(0,1,2,0),c("Marker1","Marker2","Marker3","Marker4"))
#' make_phenotype_name(c(0,1,-1),c("Marker1","Marker2","Marker3"))
#' 
#' @export
make_phenotype_name <- function(phenotype, markers) {
    .Call('_PhenoComb_make_phenotype_name', PACKAGE = 'PhenoComb', phenotype, markers)
}

#' Count markers in phenotype
#'
#' \code{count_markers} counts the number of markers a phenotype has
#' given its numerical representation. Basically it returns the number of
#' values greater than -1 in an integer vector.
#'
#' @param phenotype Numeric vector with phenotype encoding.
#' @return Number of markers.
#'
#' @examples
#' count_markers(c(0,1,2,0))
#' count_markers(c(0,1,-1))
#'
#' @export
count_markers <- function(phenotype) {
    .Call('_PhenoComb_count_markers', PACKAGE = 'PhenoComb', phenotype)
}

